name: Build, Test and Deploy
on:
  # run when the master branch is updated
  push:
    branches:
      - master

  repository_dispatch:
    types:
      - push-tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!(github.event.head_commit && contains(github.event.head_commit.message, 'ci skip'))"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false


      - name: Install NPM Dependencies
        run: npm install @qooxdoo/framework --no-save --no-package-lock

      - name: Build Icon Viewer
        run:  npx qx deploy --target=build -v --clean


      - name: Deploy Icon Viewer
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
